name: minet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.2
  - matplotlib
  - numpy
  - pandas
  - setuptools
  - build
  - psutil
  - scipy
  - statsmodels
  - tqdm
  - pip
  - pip:
    - -e ${PACKAGE_PATH}
